### ISSUE TITLE
Data Extract: No Confirmation when extract completed

### ISSUE THREAD

**Issue by rmdedios** [wrktech/community#5]
https://account.wrk.com/extract/

When extracting a JSON file under the data extract page there is no confirmation when the extract has been completed. The only way to tell is when the file appears under Data File Library, but even then you will still need to refresh the page in order to know if the file was downloaded. 

As a client/user a confirmation message when the extract is done will be useful and will prevent them from trying to extract the file multiple times. 

There is the message:

![message](https://user-images.githubusercontent.com/61804162/76144239-4931c180-604c-11ea-85d6-0c866b447826.PNG)

But it is still unclear when the file is done. 

![no confirmation when data has been extracted](https://user-images.githubusercontent.com/61804162/76144028-4930c200-604a-11ea-9884-a65af3f2636a.PNG)

**Comment by robbrit** [comment]
As I mentioned in #9 the extract  _does_ show up in the data file library (without refreshing) unless the extract fails.

It would be useful to have it more prominent though - we'd have to build a notification system on the account side which will take a bit of work but would be worth doing long-term.

**Comment by robbrit** [comment]
I'll close this ticket, but create a new one in the private repo for account notifications so that it doesn't get lost.
