### ISSUE TITLE
Launch Job page - cannot edit or remove launched jobs

### ISSUE THREAD

**Issue by rmdedios** [wrktech/community#8]
https://account.wrk.com/seed/job

After Launching a job there is no option to edit or remove the launched job in case of an error or a change. 

As a client/user is able to edit or remove a launched job is necessary if the information has changed or the job is no longer needed.

**Comment by davidli888** [comment]
This is by design, allowing a client to edit their data mid way through a sequence can create inconsistencies and it would be impossible to determine where data errors are coming from.
